# Generated by Django 4.1.2 on 2022-11-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoList", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="status",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
